#!/bin/bash

declare -r SERVICE_FILE_NAME="discord-bot.service"
# declare -r SYSTEMD_SERVICE_FILE="/etc/systemd/system/$SERVICE_FILE_NAME"
declare -r SYSTEMD_SERVICE_FILE="$SERVICE_FILE_NAME"

fatal() {
    printf >&2 '[ \033[31mFATAL ERROR\033[0m ]: %s\n' "$*";
    exit 1
}

err() {
    printf >&2 '[ \033[31mERROR\033[0m ]: %s\n' "$*";
}

write-service-file(){
    local python_path
    python_path="$(command -v python3)" || {
        fatal "Failed to find Python3 in PATH."
    }
    cat << EOF | sudo tee "$SYSTEMD_SERVICE_FILE" > /dev/null || fatal "Failed to write service file."
[Unit]
Description=Morningstar Discord Bot Service
After=network.target

[Service]
User=$USER
WorkingDirectory=$PWD
ExecStart=$PWD/venv/bin/python3 $PWD/main.py
Restart=always
RestartSec=5

[Install]
WantedBy=multi-user.target
EOF
    return 0
}

set-service-file-perms(){
    local service_file_perms
    service_file_perms=$(stat $SYSTEMD_SERVICE_FILE | perl -ne 'print $1 if m/^\s*Access: \((\d{4}).*$/')
    if [[ $service_file_perms != '0755' ]]; then
        sudo chmod 0755 "$SYSTEMD_SERVICE_FILE" || { 
            err "Failed to set service file permissions to 0755!"; return 1;
        }
    fi
    return 0
}

while [[ -n $1 && $1 =~ ^- && $1 != '--' ]]; do

    case $1 in
        -r|--remove)
            # Remove the service file
            if sudo systemctl is-active --quiet "$SERVICE_FILE_NAME"; then
                sudo systemctl disable --now "$SERVICE_FILE_NAME"
            fi
            sudo rm -f "$SYSTEMD_SERVICE_FILE" || {
                fatal "Failed to remove system service file at $SYSTEMD_SERVICE_FILE"
            }
            exit 0
            ;;

        *) fatal "Unknown option: $1" ;;

    esac
done

if ! [[ -f ./main.py ]]; then
    printf >&2 "ERROR: main.py not found in the current directory.\n\n"
    printf >&2 'Are you in the correct directory? Run from root of project directory with "./scripts/systemd-integration"\n'
    exit 1
fi

if ! [[ -f "$SYSTEMD_SERVICE_FILE" ]]; then
    write-service-file
    set-service-file-perms
else
    printf "\033[33mWARNING: Systemd file already exists. This will overwrite the current service file.\033[0m\n"
    read -r -p "Would you like to overwrite the current service file? [y/N]: " overwrite
    if [[ $overwrite == [yY] ]]; then
        printf "Overwriting current service file...\n"
        write-service-file
    else
        printf "Not overwriting current service file.\n"
    fi
fi


printf "Starting and enabling the service...\n"

if ! sudo systemctl enable --now discord-bot.service; then  
    fatal "Failed to start and enable the service. Please check the service file and try again."
fi

printf "\033[32mService started and enabled successfully.\033[0m\n"

